language: scala

scala:
   - 2.10.6
   - 2.11.8

jdk: 
   - oraclejdk8
   - oraclejdk7
   - openjdk7

matrix:
   include:
      #- scala: 2.12.1
      #  jdk: oraclejdk8

install:
   - sbt update

script:
  - sbt set\ JFX.devKit\ :=\ JFX.jdk\(\"$JAVA_HOME\"\) ++$TRAVIS_SCALA_VERSION coverage compile model/test view/test viewSwing/test sampleSwing/test coverageReport

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate coveralls
