language: scala

env:
   - EXTRA=

scala:
   - 2.10.6
   - 2.11.8

jdk: 
   - oraclejdk8
   - oraclejdk7
   - openjdk7

matrix:
   include:
      #- scala: 2.12.1
      #  jdk: oraclejdk8
      # travis can't seem to run the JavaFX tests, but it can at least compile them
      - scala: 2.11.8
        jdk: oraclejdk8
        env: EXTRA=compile

install:
   - sbt update

script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage $EXTRA model/test view/test viewSwing/test sampleSwing/test coverageReport

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate coveralls
