language: scala

scala:
   - 2.10.6
   - 2.11.8

jdk: 
   - oraclejdk8
   - oraclejdk7
   - openjdk7

matrix:
   include:
      #- scala: 2.12.1
      #  jdk: oraclejdk8

install:
   - sbt update

script:
  - sbt set\ JFX.devKit\ :=\ JFX.jdk\(\"$JAVA_HOME\"\) set\ testOptions\ in\ Test\ +=\ Tests.Argument\(\"-l\"\,\ \"com.rayrobdod.boardGame.javafxView.FxTests\"\) ++$TRAVIS_SCALA_VERSION coverage test

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coveralls
