language: scala

scala:
   - 2.10.7
   - 2.11.12
   - 2.12.6

jdk: 
   - oraclejdk8
   - oraclejdk10

before_install:
  - export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start

install:
   - |
      pushd /tmp
      git clone --branch=3.1 --depth=2 -- https://github.com/rayrobdod/json.git json
      cd json
      echo sbt.version=0.13.17>project/build.properties
      sbt ++$TRAVIS_SCALA_VERSION publishLocal
      popd
   - sbt ++$TRAVIS_SCALA_VERSION update

script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageAggregate coveralls
