version: '4.0.{build}'
os: Windows Server 2012
install:
  - cmd: choco install sbt --version 0.13.15
  - cmd: C:\cygwin64\setup-x86_64.exe --no-admin -q -P graphviz
  - cmd: refreshenv
  - |
     mkdir %USERPROFILE%\.sbt\0.13
     echo scalacOptions in doc in Compile ++= Seq("-diagrams-dot-path", """C:\cygwin64\bin\dot.exe""")>%USERPROFILE%\.sbt\0.13\dot.sbt
     echo publishTo in Global := {val patterns = if (publishMavenStyle.value) {sbt.Resolver.mavenStylePatterns} else {sbt.Resolver.ivyStylePatterns}; Some(Resolver.file("file", file("""C:\projects\boardgame\publish"""))(patterns) )}>%USERPROFILE%\.sbt\0.13\pubdir.sbt
  - |
     cd C:\projects
     git clone --branch=3.1 --depth=2 -- https://github.com/rayrobdod/json.git json
     cd json
     echo sbt.version=0.13.17>project/build.properties
     sbt ++%SCALA_VERSION% publishLocal
     cd C:\projects\boardgame
  - cmd: sbt ++%SCALA_VERSION% update

environment:
  matrix:
  - SCALA_VERSION: 2.10.7
    JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
    SBT_CROSS_TARGET: scala-2.10
  - SCALA_VERSION: 2.11.12
    JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
    SBT_CROSS_TARGET: scala-2.11
  - SCALA_VERSION: 2.12.6
    JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0
    SBT_CROSS_TARGET: scala-2.12
build_script:
  - 'sbt ++%SCALA_VERSION% compile publish'
test_script:
  # primary purpose is to package, but might as well test too, I guess.
  - cmd: 'sbt ++%SCALA_VERSION% test'
artifacts:
  - path: publish
    name: sbt_publish_directory
